# Generated by Django 3.0.5 on 2020-04-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='type_blog',
            field=models.CharField(choices=[('L', 'Linux-Unix'), ('V', 'VMWare'), ('W', 'Window'), ('P', 'Python'), ('S', 'Scripting'), ('O', 'Others')], default='L', max_length=29),
        ),
    ]
