# Generated by Django 3.0.5 on 2020-04-08 08:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_blog_type_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='abc'),
            preserve_default=False,
        ),
    ]
